export const FETCH_POSTS = "FETCH_POSTS"
export const FETCH_SINGLE_POST = "FETCH_SINGLE_POST"

export const FETCH_USERS="FETCH_USERS"
export const FETCH_SINGLE_USER =  "FETCH_SINGLE_USER"

export const POST_COMMENT = "POST_COMMENT"
export const FETCH_POSTS_COMMENTS = "FETCH_POSTS_COMMENTS"
export const FETCH_IMAGE="FETCH_IMAGE" 

